### ISSUE TITLE
Adding OS Versions to Simulator Labels

### ISSUE THREAD

**Issue by slowbrewedmacchiato** [sweetpad-dev/sweetpad#14]
It would be really nice to add the OS version being ran to the simulator labels. For example, there are cases where one might have multiple iPhone 15 Pro simulators. In that case, it is worth knowing which one is being launched.

In Xcode for example, we normally have <device>(<os_version>). As an example:

- iPhone 15 Pro (17.2)
- iPhone 15 Pro (17.4)

It took me launching multiple times to finally find the right simulator I wanted to launch.

To better visualize, what I mean, here's an example:

<img width="693" alt="Screenshot 2024-06-04 at 11 01 21" src="https://github.com/sweetpad-dev/sweetpad/assets/861555/8007c682-986b-4712-9c0e-33a997c8e550">

This would also apply to the Simulators side bar where we have a full list, but in case one had tons of simulators of the same device but different OS versions, it becomes difficult to know which is which.

Great extension otherwise. Thank you!

**Comment by hyzyla** [comment]
Thanks! Definitely makes sense.  I going to add it in the next release

**Comment by slowbrewedmacchiato** [comment]
Appreciate it! I am going to use it 100% for my work today and see if there are additional feedbacks to provide. Looking forward to the next release version.

**Comment by hyzyla** [comment]
iOS version was added to the simulators list in 	0.1.19 version

**Comment by slowbrewedmacchiato** [comment]
I just updated and this works! Thanks a bunch for the quick turn around!
