### ISSUE TITLE
configurable DerivedDataPath

### ISSUE THREAD

**Issue by aelam** [sweetpad-dev/sweetpad#21]
does it support configurable DerivedDataPath

it seems right now sweetpad is using the default path 
which means the xcode-build-server has to have the build_root same as the default path.
otherwise autocompletion can not work 
and since every team member may have different default path, this file can not be committed to the repo

**Comment by hyzyla** [comment]
Hello! Currently it's not configurable, but it is fairly easy to add option to VSCode settings.json. I'll try to implement  it today-yesterday

**Comment by hyzyla** [comment]
@aelam check this [Set DerivedData path](https://github.com/sweetpad-dev/sweetpad/blob/main/docs/wiki/build.md#set-deriveddata-path). I uploaded new version of the extension with that configuration few minutes minutes ago, so probably you will need to update extension manually to check this feature

**Comment by aelam** [comment]
very rapid, Thanks for your hard work. 
I will try!

**Comment by hyzyla** [comment]
Closing this issue for now. Feel free to reopen it if something doesn't work 🤝
