### ISSUE TITLE
is it better/possible to add a recent simulators section

### ISSUE THREAD

**Issue by aelam** [sweetpad-dev/sweetpad#22]
there are so many simulators 
including Watch, iPhone, plus old ones from one Xcode

and actually users dont know which simulator is active
I feel iOS-debug way is simple and clean 
do you have any idea

**Comment by hyzyla** [comment]
Hello! Thanks for the valuable feedback. There is definitely room for improvement for the simulators view. Here are some ideas to improve it:

1. Remove non-iPhone/iPad simulators, like Apple Watch and Apple TV.
2. Put recently used simulators at the top of the list.
3. Remove unavailable runtimes.
 4. ... what else?

Could you also share how your list of devices looks in the Sweetpad extension and the iOS-debug extension for reference?

**Comment by aelam** [comment]
I refer to Xcode list
here is the scenario.
1. I choose a scheme. the scheme target is determined. so I know the list should only list iPhone or iPhone Simulator or generic iPhone or generic iPhone Simulator
  * same for watch scheme
2. then choose a target 

| User-Scheme |  target |

the scheme drop down menu and target drop down menu might be a good solution
and they should show in the UI maybe in the bottom or somewhere


<img width="339" alt="Screenshot 2024-07-07 at 0 36 09" src="https://github.com/sweetpad-dev/sweetpad/assets/232337/287ff2f7-f9f1-4b8c-a28a-81ac72b85177">

**Comment by hyzyla** [comment]
I've published a new version of the extension, 0.1.24, which includes a "Recent" section. Inside this section, destinations are sorted by usage frequency

![CleanShot 2024-07-21 at 17 25 48@2x](https://github.com/user-attachments/assets/72ed9ab9-1eac-4034-b853-79e527bb5b38)
