### ISSUE TITLE
[Discussion]show selected "workspace" "scheme' in status bar

### ISSUE THREAD

**Issue by aelam** [sweetpad-dev/sweetpad#28]
I'm thinking if it's better to show the selected workspace -- selected scheme in the status bar

## Benefits
1. engineer can understand the current context easily
2. the future test explorer could be narrowed down to the selected workspace&scheme
   * one bad practice of xcode project : some people shared the same test in different targets

## bad point?
maybe some engineers want to show all the test cases of all schemes.

**Comment by hyzyla** [comment]
nice idea! just few minutes ago published new version with that bar

![CleanShot 2024-07-22 at 21 15 10@2x](https://github.com/user-attachments/assets/560b2267-4acc-4117-ab6d-77a5dcb1a2a7)
