### ISSUE TITLE
[Discussion]saving lastBuild in workstate might be better

### ISSUE THREAD

**Issue by aelam** [sweetpad-dev/sweetpad#29]
Just opinion

currently the lastBuild in the session

I think saving in the workspace state might be better.
because if I close the vscode and reopen it the lastBuild is not available 

and the behavior actually the same as Xcode if saving in workspace state, even if it's an outdated build, I would be still OK with it

**Comment by hyzyla** [comment]
Could you explain what you mean by `lastBuild`? Is it related to `build.lastLaunchedAppPath` for the debugger?

**Comment by aelam** [comment]
I meant `getAppPath`, 
just help launch lldb with the path `${command:sweetpad.debugger.getAppPath}`
if it's failed, showing a dialog might be enough

**Comment by hyzyla** [comment]
I've added saving build.lastLaunchedAppPath in latest release. Could you check? https://github.com/sweetpad-dev/sweetpad/commit/4fa38f8909e2c48bb406690ecbc84099170b76ef

**Comment by aelam** [comment]
can it be set in launch.json? 

right now there are two settings
which one i should use 

${command:sweetpad.debugger.getAppPath

**Comment by hyzyla** [comment]
I think there are no other way for extension to provide path, only command can work https://code.visualstudio.com/docs/editor/variables-reference

**Comment by aelam** [comment]
never mind, 
https://github.com/sweetpad-dev/sweetpad/commit/4fa38f8909e2c48bb406690ecbc84099170b76ef
is very good.

Thanks for your effort

**Comment by hyzyla** [comment]
Thank you for feedback!
