### ISSUE TITLE
When running sweetpad:build/test/clean, it reports KNOWN_ISA[obj.isa] is not a function

### ISSUE THREAD

**Issue by potterdai** [sweetpad-dev/sweetpad#32]
Hi there,

When running sweetpad:build/test/clean, it reports "KNOWN_ISA[obj.isa] is not a function".
<img width="477" alt="Screenshot 2024-08-04 at 00 58 10" src="https://github.com/user-attachments/assets/c3b593e4-8b70-4388-9e91-c35fc6d4b43a">

The other commands work fine.

It's not repro if I create a new project, so I guess it's project specific. Is there a way to debug this? It looks like some random strings were parsed as a function.

Thank you for the amazing work!

**Comment by hyzyla** [comment]
Hello! Wow, I've never seen such an error before! A quick search suggests it might be a problem with the third-party library @bacons/xcode that I use to parse Xcode project files. You can see more details here [[1]](https://github.com/EvanBacon/xcode/blob/4046ef4db7a90b37b0e0b9106e2178401393c271/src/api/XcodeProject.ts#L240)

1. Could you share your *.pbxproj file?
2. If you can't do that, could you share a full list of all "isa" in your *.pbxproj using: grep 'isa' **/*.pbxproj
3. The last thing you can do is try to debug the extension yourself. I've just made a tutorial on how to do it [[2]](https://github.com/sweetpad-dev/sweetpad/blob/main/docs/dev/debug.md)

**Comment by potterdai** [comment]
Thank you for your help! It might be because I am using Xcode 16 beta, which introduced a new enum type: PBXFileSystemSynchronizedRootGroup. This is not properly handled here: [XcodeProject.ts](https://github.com/EvanBacon/xcode/blob/4046ef4db7a90b37b0e0b9106e2178401393c271/src/api/XcodeProject.ts#L71).

**Comment by potterdai** [comment]
I have created an issue on @bacons/xcode: https://github.com/EvanBacon/xcode/issues/17

A similar issue can be found here: https://github.com/CocoaPods/CocoaPods/issues/12456

**Comment by hyzyla** [comment]
Yeah, I find a repository with which runs perfectly in Xcode16, but have the same error in the extension

**Comment by potterdai** [comment]
Agreed! This issue will only occur if there is a folder group in the project.

[Learn more about how synchronized groups work at the pbxproj level.](https://pepicrft.me/blog/2024/07/20/how-synchronized-groups-work-at-the-pbxproj-level)

This feature is super handy, and I feel it will greatly boost development in VSCode as well. Hopefully, @EvanBacon/xcode can update it. =)

**Comment by rudrankriyam** [comment]
Even after replacing `PBXFileSystemSynchronizedRootGroup`, I have not been able to solve it. Any ideas?

**Comment by hyzyla** [comment]
@rudrankriyam @potterdai, I've added fallback parser to avoid issue with xcode16 and published it under version v0.1.29. Could you update and try it again?
