### ISSUE TITLE
No such module 'UIKit'

### ISSUE THREAD

**Issue by RadioHeadach** [sweetpad-dev/sweetpad#33]
Hi there!

First of all, sweetpad is such a great job, especially since JetBrain no longer keep the maintenance of AppCode. It's such a relief just install then everything runs smoothly with all xcode & swift dependencies.

Recently I found an issue, it prompts an alert shows that No such module 'UIKit', which makes code completion fails.
![image](https://github.com/user-attachments/assets/6be93b7f-622c-4c50-84d5-287ca352830e)

I found that if I do the following and this issue will fix itself for a minute or so, but after a short time it will rise again:
1. delete all the `*.xcodeproj` and `*.xcworkspace` files generate them again with xcodegen
2. build & run the project with sweetpad

Additionally, this issue only happens to UIKit, other "imports" are good, such as Foundation, CoreLocation, or any dependencies from cocoapods.

Again, really appreciate your great job!!!

**Comment by N-Joy-Shadow** [comment]
Do you have a Build Server Config configured?
If not, run the command `SweetPad: Generate Build Server Config`

**Comment by RadioHeadach** [comment]
> Do you have a Build Server Config configured? If not, run the command `SweetPad: Generate Build Server Config`

I tried delete the Build Server Config then re-generate it with SweetPad command, but it didn't help.

**Comment by RadioHeadach** [comment]
> Do you have a Build Server Config configured? If not, run the command `SweetPad: Generate Build Server Config`

Thanks for your information!! I found `SweetPad: Generate Build Server Config` command keep generating `Build Server Config` with **wrong scheme name** based on my history scheme name.

I fixed this issue by manually executing `xcode-build-server`'s command `xcode-build-server config -workspace *.xcworkspace -scheme XXX`, then UIKit is found and no more error show up.
