### ISSUE TITLE
Debugger can't attach to iOS app running in simulator

### ISSUE THREAD

**Issue by yevhen** [sweetpad-dev/sweetpad#35]
Hi, Yevhenii!

First of all, I want to send KUDOS to you for such incredible work!
This is a much-needed extension that will make many people much happier. 
What could be better than escaping archaic Xcode to an all-modern VSCode with Copilot? ))

I've tried it over the weekend and got everything working except debugging. Which is a pity, of course(
While launching an app from Sweetpad created launch.json, the app is built, installed, and launched without problems, but then the debugger fails with:

<img width="293" alt="debugger fail" src="https://github.com/user-attachments/assets/ccd2e59d-8640-453a-a1a5-da2f761d3795">

I've checked out the outputs of Sweetpad and CodeLLDB and haven't found anything suspicious.
Have you seen this error before? It could be something local (with my dev env), but I can't figure out what could be the source.

P.S. I've found and tried some resolutions on SO but with no luck

**Comment by yevhen** [comment]
Disregard. I've fixed it by removing the CodeLLDB extension and then installing the ARM64 version directly from .vsix.

**Comment by hyzyla** [comment]
Oh thanks for letting me know! Just for historical reference. Do you have arm64 or x86_64 macOS?

**Comment by yevhen** [comment]
Arm64. I think the problem might be the fact that I migrated from Intel-based mbp using apple migration assistant and might just copied x64 based llldb debugger with VSCode. I’ve reinstalled VSCode to match the arch, but extensions live their own life and I guess need to be reinstalled separately.
