### ISSUE TITLE
Feature Request: Add support for -skipMacroValidation flag

### ISSUE THREAD

**Issue by LukaZeleznik** [sweetpad-dev/sweetpad#36]
Request to add support for the `-skipMacroValidation` flag to SweetPad, allowing users to bypass macro validation during build.

Currently, sweetpad does not allow the user to set a `-skipMacroValidation`, which is needed in some workspaces. Otherwise the build might fail with:

> The following build commands failed: ComputeTargetDependencyGraph

We use TCA, so this command is needed for a successful build.

Proposed Solution
Add the option to add `-skipMacroValidation` flag that allows users to skip the macro validation step when building.

**Comment by hyzyla** [comment]
Make sense, I will definitely add it to the next release

**Comment by hyzyla** [comment]
I've added support for this in the latest release 0.1.28. Here is documentation — [Set additional build settings](https://sweetpad.hyzyla.dev/docs/build#set-additional-build-settings)

Briefly you need to add this to your `.vscode/settings.json` file:
```json
{
  "sweetpad.build.args": ["-skipMacroValidation"],
}
```

**Comment by LukaZeleznik** [comment]
Thank you very much!
