### ISSUE TITLE
Build & Run (Launch) failing

### ISSUE THREAD

**Issue by schwjustin** [sweetpad-dev/sweetpad#38]
When I try to build and run I get this error: Sweetpad: Cannot read properties of undefined (reading 'startsWith')

```
...
\n      \"XCODE_VERSION_MAJOR\" : \"1500\",\n      \"XCODE_VERSION_MINOR\" : \"1520\",\n      \"XPCSERVICES_FOLDER_PATH\" : \"Test.app/XPCServices\",\n      \"YACC\" : \"yacc\"\n    },\n    \"target\" : \"Test\"\n  }\n]",
  "stderr": "2024-09-10 19:00:32.552 xcodebuild[59969:5122444] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition",
  "command": "xcodebuild",
  "args": [
    "-showBuildSettings",
    "-scheme",
    "Test",
    "-workspace",
    "/Users/justinschwartz/Developer/Test/test/Test.xcodeproj/project.xcworkspace",
    "-configuration",
    "Debug",
    "-json"
  ],
  "cwd": "/Users/justinschwartz/Developer/Test/test"
}
{
  "message": "Cannot read properties of undefined (reading 'startsWith')",
  "level": 3,
  "time": "2024-09-10T23:00:32.881Z",
  "command": "sweetpad.build.launch",
  "error": {}
}
```

![Screenshot 2024-09-10 at 6 59 49 PM](https://github.com/user-attachments/assets/b920f4e5-94b5-4d65-9319-072460abfba5)

**Comment by hyzyla** [comment]
Hello! Thank you for reporting issue!

Unfortunately, the error message in the logs is quite unclear about where it happened. Could you manually run this command in your project directory and send me the output you get?

```bash
cd /Users/justinschwartz/Developer/Test/test
xcodebuild -showBuildSettings -scheme Test -workspace /Users/justinschwartz/Developer/Test/test/Test.xcodeproj/project.xcworkspace -configuration Debug -json

```

**Comment by hyzyla** [comment]
Hi. You can email me hyzyla@gmail.com

**Comment by shaharukhs** [comment]
I am also facing the same issue with VS Code extension.

**Comment by hyzyla** [comment]
@schwjustin I've added better error handling in all places where I'm calling .startsWith. Also I've added sentry reporting (disabled by default). Could you update extension (0.1.30), enable sentry reporting in .vscode/settings.json and try again?:
```json
{
    "sweetpad.system.enableSentry": true,
}
```
