### ISSUE TITLE
Issue with running on device

### ISSUE THREAD

**Issue by rudrankriyam** [sweetpad-dev/sweetpad#40]
I am trying to build it on device. Simulator works perfectly but I am getting the following error: 

```
** BUILD SUCCEEDED ** [20.524 sec]

🚀 Executing command:
xcrun devicectl device install app --device 00008120-000A1C992E50C01E /Users/rudrankriyam/Library/Developer/Xcode/DerivedData/Meshing-dlhegtlubpdtxdatwwbgjjrmxzjk/Build/Products/Debug-iphoneos/Meshing.app/Meshing

ERROR: Failed to install the app on the device. (com.apple.dt.CoreDeviceError error 3002 (0xBBA))
       NSLocalizedFailureReason = The provided item to be installed is not of a type that CoreDevice recognizes.
       NSURL = file:///Users/rudrankriyam/Library/Developer/Xcode/DerivedData/Meshing-dlhegtlubpdtxdatwwbgjjrmxzjk/Build/Products/Debug-iphoneos/Meshing.app/Meshing

🚫 Command returned non-zero exit code
```

Any idea why it cannot recognize the device? I am running iOS 18 R C and Xcode 16.0 R C

**Comment by hyzyla** [comment]
Thanks for reporting the issue. I'll wait for iOS 18 release for few days to update my phone. Then I'll try to reproduce the issue

**Comment by hyzyla** [comment]
Sorry for that, I've made silly mistake in previous commits. Fixed in v0.1.33

**Comment by hyzyla** [comment]
@schwjustin I use devicectl to install and launch app on device and seems like --console option was added in Xcode 16. So it's not hard to add it to extension. Or do you mean another kind of of logs, not from stdout/stderr?

![image](https://github.com/user-attachments/assets/e0e32ef0-3d98-4efa-8d8d-33578b714516)

**Comment by hyzyla** [comment]
@schwjustin In the latest version (0.1.34), I've added the --console option for launching on physical devices. This option will redirect stdout to the extension, allowing you to print debug information on a physical device.

    --console — Attaches the application to the console and waits for it to exit. devicectl will wait for the app to terminate. Catchable signals sent to devicectl are forwarded to the app. If the app is not already running, its standard streams will be connected to devicectl's standard streams.
