### ISSUE TITLE
when a project has installed pod , sweetpad can't build in cursor.

### ISSUE THREAD

**Issue by banelin8814** [sweetpad-dev/sweetpad#44]
![截圖 2024-09-24 下午5 17 14](https://github.com/user-attachments/assets/95b84c0e-37cc-48bf-9790-d62980d98e72)

**Comment by hyzyla** [comment]
Hello 👋 

Make sure that pods are installed:

```
pod install

```

And make sure that you've selected correct workspace by executing that command in command palette:
```
> SweetPad: Select Xcode Workspace
```

And choose recommended *CocoaPods* workspace
