### ISSUE TITLE
VisionOS simulators?

### ISSUE THREAD

**Issue by tvidenov** [sweetpad-dev/sweetpad#51]
Any plans to support VisionOS's simulator and perhaps physical device?

**Comment by hyzyla** [comment]
Yeah, I would like to add visionOS support, but I haven't yet tried to build and run any projects with visionOS using the xcodebuild CLI tool (the extension uses it to build the project). From my understanding, visionOS has similarities with iOS, so if my assumption is correct and xcodebuild CLI supports it, then adding visionOS support shouldn't be a problem

**Comment by rudrankriyam** [comment]
Let me know! I was looking for it right now, and saw the // TODO for xrOS; happy to test for the visionOS simulator! Something alone the lines: 

```bash
xcodebuild build -scheme MyScheme -destination platform=visionOS Simulator,name=Apple Vision Pro
```

**Comment by hyzyla** [comment]
Hi! I've added basic visionOS simulator support in version 0.1.39.

For the physical visionOS device support, I need to add watchOS first, and then later apply the same changes to for visionOS
