### ISSUE TITLE
[Feature request] Add configuration for default scheme for tests

### ISSUE THREAD

**Issue by rpedretti** [sweetpad-dev/sweetpad#60]
On my project we have multiple build schemes but the tests run on only one of them and most of the time, if not all, I develop and run the app on one scheme and run the tests on another one.

 we could have the default test scheme, similar to the existing default run scheme, to not have to switch schemes to run the tests.
 
And it might be possible to use 
```
xcodebuild test-without-building \
    -workspace <workspace> \
    -scheme <scheme for testing> \
    -destination <dest> \
    -enumerate-tests \
    -test-enumeration-format json \
    -test-enumeration-output-path <path to result>
```
to get the correct test plan and show the tests on test explorer also

**Comment by hyzyla** [comment]
Oh, interesting insight! I think it would be great to use the 'ask' scheme by default and store it in a separate context value than the one we have for the build. Additionally, for users who prefer configuration files, it would be good to provide the option to define the scheme in `.vscode/settings.json`

**Comment by hyzyla** [comment]
I've added few additional commands in v0.1.40:
```jsonc
      {
        "command": "sweetpad.testing.setDefaultScheme",
        "title": "SweetPad: Set scheme for testing",
        "icon": "$(file-code)"
      },
      
      {
        "command": "sweetpad.destinations.selectForTesting",
        "title": "SweetPad: Select destination for testing",
        "icon": "$(file-code)"
      }
```

Also "configuration" (Debug, Release) option is also separated for "launch" and "build" contexts

**Comment by rpedretti** [comment]
Amazing! I already updated the extension and it's soooo helpful!
