### ISSUE TITLE
There are no simulators for tvOS

### ISSUE THREAD

**Issue by Ernest0-Production** [sweetpad-dev/sweetpad#61]
There is no way to build and run applications for tvOS

![CleanShot 2024-10-28 at 01 17 46@2x](https://github.com/user-attachments/assets/30969c0b-01db-4bdf-93df-5754fcf038d0)

**Comment by hyzyla** [comment]
Hello! Thank you for opening the issue. I recently added tvOS support in version 0.1.41

**Comment by Ernest0-Production** [comment]
And thank you, @hyzyla!
