### ISSUE TITLE
Error when adding an assets catalog to an SPM package

### ISSUE THREAD

**Issue by florianpeninon** [sweetpad-dev/sweetpad#62]
When using an SPM package to modularize an app, adding an asset catalog (even an empty one) as a resource in the package makes most of the tasks fail with the following error:
> SyntaxError: Unexpected non-whitespace character after JSON at position X (line X column X)

**Comment by florianpeninon** [comment]
Update: I relocated my asset catalog and the error disappeared.
I will assume the error was unrelated to the addition of the catalog asset, but FWIW the error message wasn't helpful to figure out what the problem was from the start.

**Comment by hyzyla** [comment]
Thanks! Could you give basic idea how and where have you added asset catalog? I’ll try to check later to provide more useful message for error or even handle that situation

**Comment by florianpeninon** [comment]
I initially added the asset catalog at the root of my package `MyApp/MyAppLib/Resources/Assets.xcassets` instead of adding it at the root of my target `MyApp/MyAppLib/MyTarget/Resources/Assets.xcassets`.

With the catalog in the wrong place I could build & run the application in Xcode but couldn't with SweetPad.
What tipped me in the right direction was an error message in the console when running the app (something along the line of couldn't find the asset).
