### ISSUE TITLE
Files out of sync with xcode/cursor/vscode

### ISSUE THREAD

**Issue by iamhenry** [sweetpad-dev/sweetpad#78]
Files were working before but as i added new ui buttons i noticed it stopped working and I build and relaunch

i'm working on a mac app and when i build and relaunch the ui doesnt get updated

it seems like some files are out of sync and sweetpad is building an old version?

what do i need to do to ensure the changes i save are the changes in the latest build?

### Xcode error
![Screenshot 2024-11-18 at 1 55 32 PM](https://github.com/user-attachments/assets/41569d3c-dec5-4226-9680-b17506cacafb)
---
### recent code not reflecting in the UI
![image](https://github.com/user-attachments/assets/bffa28e1-1609-47a1-8c8a-16785dc7eebd)
---
### recent build without the updated code taking effect
![image](https://github.com/user-attachments/assets/ab080377-c5fd-4cb7-9aa5-fe8c31b49bbb)

**Comment by iamhenry** [comment]
i hadnt manually added the new files created in vscode to xcode

that resolved my issue

**Comment by hyzyla** [comment]
Also, higly recommend this article https://dimillian.medium.com/why-you-should-use-xcode-16-buildable-folders-instead-of-groups-6f438611914d
