### ISSUE TITLE
esbuild fails when SENTRY_DSN environment variable is not defined

### ISSUE THREAD

**Issue by ScriptBloom** [sweetpad-dev/sweetpad#83]
### Problem
The esbuild build fails when the `SENTRY_DSN` environment variable is not defined, with the error:

### Root Cause
1. esbuild's define option requires all values to be JSON serializable
2. When `process.env.SENTRY_DSN` is undefined, it results in an `undefined` value which is not a valid JSON value

**Comment by hyzyla** [comment]
Thanks for highlighting it. I have SENTRY_DSN set in my system, so I didn't notice it before. I've updated the code, could you try it now?

**Comment by ScriptBloom** [comment]
> Thanks for highlighting it. I have SENTRY_DSN set in my system, so I didn't notice it before. I've updated the code, could you try it now?

Thanks, now it's OK, I'll close this pr: https://github.com/sweetpad-dev/sweetpad/pull/84
