### ISSUE TITLE
Feature Request: Support Launch Arguments and Environment Variables

### ISSUE THREAD

**Issue by FelixLisczyk** [sweetpad-dev/sweetpad#96]
Currently, the SweetPad extension doesn't support setting launch arguments and environment variables when launching apps. While the extension supports basic app launching through the `sweetpad-lldb` configuration type, developers need more control over the app's launch configuration for different development scenarios.

## Current Configuration
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "sweetpad-lldb",
      "request": "launch",
      "name": "Attach to running app (SweetPad)",
      "preLaunchTask": "sweetpad: launch",
    },
  ],
}
```

### Option 1: Enhanced Launch Configuration
Extend the existing configuration to include launch arguments and environment variables:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "sweetpad-lldb",
      "request": "launch",
      "name": "Launch App (SweetPad)",
      "preLaunchTask": "sweetpad: launch",
	  "scheme": "My Scheme",
      "launchArguments": [
        "-skipOnboarding",
        "-unlockFeatureX"
      ],
      "environmentVariables": {
        "OS_ACTIVITY_MODE": "disable",
        "OTHER_VAR": "value"
      }
    },
  ],
}
```

### Option 2: Automatic Xcode Scheme Parser
- Parse launch arguments and environment variables directly from the Xcode project/scheme configuration
- No additional configuration needed in launch.json if using existing Xcode/XcodeGen/Tuist settings

## Technical Considerations
- Environment variables for the simulator must be prefixed with `SIMCTL_CHILD_` ([Source](https://stackoverflow.com/questions/34618580/xcrun-is-there-a-way-to-set-environment-variable-via-xcrun-simctl-cli))
- The extension should handle this prefix automatically
- (Option 1) Support for multiple launch configurations in the same workspace

## Use Cases
1. Control feature flags during development:
   - Skip onboarding flows
   - Toggle feature states
   - Control unlock states

2. Configure debugging environment:
   - Set logging levels via `OS_ACTIVITY_MODE`
   - Control debug output verbosity
   - Set test environment variables

## Benefits
- Improved development workflow parity with Xcode
- More efficient testing of different app states
- Better debugging capabilities through environment control
- (Option 2) Seamless integration with existing Xcode/XcodeGen/Tuist configurations

**Comment by hyzyla** [comment]
@FelixLisczyk, thank you for submitting this issue. Option 2 is definitely a great idea, but it’s likely the next step. In the new version of the extension, I’ve added launchArgs and launchEnv to task definitions and settings configurations. For your example you need to create separate task "tasks.json" and then use it as `preLaunchTask` in "launch.json"

./vscode/tasks.json
```jsonc
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "sweetpad",
      "action": "launch",
      "problemMatcher": [
        "$sweetpad-watch",
        "$sweetpad-xcodebuild-default",
        "$sweetpad-xcbeautify-errors",
        "$sweetpad-xcbeautify-warnings"
      ],
      "label": "sweetpad: my launch",   // This is the name for preLaunchTask task
      "detail": "Build and Launch the app",
      "isBackground": true,
      "launchArgs": ["-skipOnboarding", "-unlockFeatureX"],
      "launchEnv": {
        "OS_ACTIVITY_MODE": "disable",
        "OTHER_VAR": "value"
      }
    }
  ]
}
```

./vscode/launch.json
```jsonc
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "sweetpad-lldb",
      "request": "launch",
      "name": "Attach to running app (SweetPad)",
      "preLaunchTask": "sweetpad: my launch"
    }
  ]
}
```

1. [Customise "preLaunchTask"](https://sweetpad.hyzyla.dev/docs/debug#customise-prelaunchtask)
2. [Set additional launch arguments and environment variables](https://sweetpad.hyzyla.dev/docs/build#set-additional-launch-arguments-and-environment-variables)
3.

**Comment by FelixLisczyk** [comment]
Thank you for implementing this so quickly! I've tested it on both iOS and macOS, and it works great so far.
